---
title: "projet_ri"
author: "Baraka Samia"
date: "24/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installation des packages : 
```{r}
install.packages("reutils")
install.packages("tm")  # pour le text mining
install.packages("SnowballC") # pour le text stemming
install.packages("wordcloud") # générateur de word-cloud 
install.packages("RColorBrewer") # Palettes de couleurs
library("tm")
library("SnowballC")
library(wordcloud)
library(RColorBrewer)
library(reutils)
```


```{r}
# Demander à l'utilisateur de tapez les terms de la requete 
print("entrer votre terms")
terms <- scan(what = "")
terms
#transformé terms en list ( append) 
#ajouter une boucle 


# faire une recherche sur pubmed : 
pmid <- esearch(terms, "pubmed" , retmax = 100 , retstart = 0 , sort= "relevance",usehistory = TRUE )
pmid

# récuperer le contneue des id renvoyés 
articles <- efetch(pmid , retmax = 100 , retstart = 0)

# récuper les valeurs de titre et résumé 
titles <- articles$xmlValue("//ArticleTitle")
abstracts <- articles$xmlValue("//AbstractText")

#List pour les titres : 
title_list <- list(titles = c(titles))
taille_list <- length(title_list$titles)
taille_list

# boucle pour parcourir la list : 
for (element in title_list) {
  print(title_list$titles)
}
#List pour les résumés : 
abstract_list <- list(abstract= c(abstracts))
taille_asbtrct_list <- length(abstract_list$abstract)
taille_asbtrct_list
# boucle pour parcourir la list : 
for (element in abstract_list) {
  print(abstract_list$abstract)
}
```

#Annexe 
```{r}
#write(content(pmid), file = "pmid.xml")

# ## Associate new search results with the existing search results.
#pmid2 <- esearch("Chlamydia psittaci[titl] and 2012[pdat]", "pubmed",
#                 usehistory = TRUE, webenv = webenv(pmid))
#pmid2

```



```{r}
# Charger les données comme un corpus
docs <- Corpus(VectorSource(title_list$titles))
inspect(docs)
```


```{r}
#Transformation : 
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

```

```{r}
# Convertir le texte en minuscule
docs <- tm_map(docs, content_transformer(tolower))
# Supprimer les nombres
docs <- tm_map(docs, removeNumbers)
# Supprimer les mots vides anglais
docs <- tm_map(docs, removeWords, stopwords("english"))

# Supprimer les ponctuations
docs <- tm_map(docs, removePunctuation)
# Supprimer les espaces vides supplémentaires
docs <- tm_map(docs, stripWhitespace)
# Text stemming
docs <- tm_map(docs, stemDocument)
docs
```


```{r}
#construir matrice term-doc
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
#matrice_exp <- m %*% t(m) 
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
dic <- data.frame(word = names(v))

#Vocabulaire (liste des mots) : 
View(dic)
```

```{r}
findFreqTerms(dtm, lowfreq = 4)
barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Most frequent words",
        ylab = "Word frequencies")
```


```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```


